name: Python CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Python Coverage
        uses: orgoro/coverage@v3
      - name: Python Actions Collection
        uses: microsoft/action-python@0.2.0


