name: Python CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: "Install poetry"
        run: |
          pip install poetry

      - name: "Install dependencies"
        run: |
          make install
          make build
          make publish
          make package-install

      - name: "Run linters"
        run: |
          make lint

      - name: "Run tests"
        run: |
          make test

      - name: "Code coverage"
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: "Test"
        run: |
          make coverage test

      - name: "Sending reporter"
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_REPORTER_ID }}
        run: |
          ./cc-test-reporter after-build -r "$GITHUB_TOKEN" --coverage-input-type=coverage.py

#      - name: Run Snyk to check for vulnerabilities
#        uses: snyk/actions/node@master
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


